### Recuperar todos las habilidades
GET http://localhost:3000/abilities

### Recuperar una habilidad por id
GET http://localhost:3000/abilities/65767c7964ff462fe7ecd504

### Recuperar todas las habilidades por nombre
GET http://localhost:3000/abilities?nombre=

### Crear una habilidad
POST http://localhost:3000/abilities
Content-Type: application/json

{
      "name": {
        "spanish": "Velo arena",
        "english": "Sand Veil"
      },
      "info": "Aumenta su evasión durante las tormentas de arena."
}

### Borrar una habilidad
DELETE http://localhost:3000/abilities/65774f30905919fbb3ed2d2d

### Actualizar una habilidad
PATCH http://localhost:3000/abilities/65767c7964ff462fe7ecd504
Content-Type: application/json

{
  "name": {
    "spanish": "Absorbe fuego",
    "english": "Flash Fire"
  }
}


