### Recuperar todos las habilidades
GET http://localhost:3000/abilities

### Recuperar una habilidad por id
GET http://localhost:3000/abilities/65651aeec8b8fffd9c697b58

### Recuperar todas las habilidades por nombre
GET http://localhost:3000/abilities?nombre=i

### Crear una habilidad
POST http://localhost:3000/abilities
Content-Type: application/json

{
      "nameSp": "aguante",
      "nameEn": "aguante",
      "description": "Pone nervioso al rival y le impide usar bayas."
}

### Borrar una habilidad
DELETE http://localhost:3000/abilities/6567e772aea15d551bc9aac6

### Actualizar una habilidad
PATCH http://localhost:3000/abilities/6564d3c88a1a0258389d4757
Content-Type: application/json

{
      "nameSp": "Ignorante"
}

