### Recuperar todos los movimientos
GET http://localhost:3000/moves

### Recuperar un movimiento por id
GET http://localhost:3000/moves/6548211649402378633eecea

### Recuperar todos los movimientos por tipo y nombre
GET http://localhost:3000/moves?nombre=a&&tipo=en

### Crear un movimiento
POST http://localhost:3000/moves
Content-Type: application/json

{
    "nameSp": "Malicioso",
    "nameEn": "Leer",
    "type": "normal",
    "class": "estado",
    "power": null,
    "accuracy": 100,
    "pp": 30,
    "description": "Intimida al objetivo con una mirada torva para reducir su Defensa.",
    "mt": null
}

### Borrar un movimiento
DELETE http://localhost:3000/moves/65482f777d70a0397d93b7f2

### Actualizar un movimiento
PATCH http://localhost:3000/moves/65482f777d70a0397d93b7f2
Content-Type: application/json

{
  "nameEn": "onda vital"
}

