### Recuperar todos los movimientos
GET http://localhost:3000/moves

### Recuperar un movimiento por id
GET http://localhost:3000/moves/6548211649402378633eecea

### Recuperar todos los movimientos por tipo y nombre
GET http://localhost:3000/moves?nombre=o&&tipo=fu

### Crear un movimiento
POST http://localhost:3000/moves
Content-Type: application/json

{
    "nameSp": "kame hame ha",
    "nameEn": "onda vital",
    "type": "agua",
    "class": "especial",
    "power": 200,
    "accuracy": 100,
    "pp": 5
}

### Borrar un movimiento
DELETE http://localhost:3000/moves/65482f6b04de6c92661b425b

### Actualizar un movimiento
PATCH http://localhost:3000/moves/65482f777d70a0397d93b7f2
Content-Type: application/json

{
  "nameEn": "onda vital"
}

