### Recuperar todos los Pokémon
GET http://localhost:3000/pokemon?nombre=&&tipo=

### Recuperar un Pokémon por id
GET http://localhost:3000/pokemon/656525b8c8b8fffd9c697b6d

### Crear un Pokémon
POST http://localhost:3000/pokemon
Content-Type: application/json

{
  "nationalNumber": 228,
      "name": "Houndour",
      "form": null,
      "generation": "ii",
      "types": [
        "siniestro",
        "fuego"
      ],
  "stats": {
        "hp": 45,
        "attack": 60,
        "defense": 30,
        "specialAttack": 80,
        "specialDefense": 50,
        "speed": 65
      },
  "height": 10.8,
  "weight": 0.6,
  "sprites": {
        "base": "https://img.pokemondb.net/sprites/scarlet-violet/normal/houndour.png",
        "home": {
          "normal": "https://img.pokemondb.net/sprites/home/normal/houndour.png",
          "shiny": "https://img.pokemondb.net/sprites/home/shiny/houndour.png"
        }
      },
  "pokedex":{
    "versions": [
      { "name": "Paldea", "number": 25 },
      { "name": "Noroteo", "number": 123 }
    ],
    "entries": [
      {
        "game": "Escarlata",
        "info": "Tiene suficiente inteligencia para cazar en manada. Se comunica con los demás a través de diversos aullidos."
      },
      {
        "game": "Púrpura",
        "info": "Usa diferentes tipos de aullidos para comunicarse con los de su especie o para perseguir a su presa."
      }
    ]
  },
  "abilities": {
        "normal": ["65767c7964ff462fe7ecd504", "65767caf5d1ec02331a6d159"],
        "hidden": "65767ce25d1ec02331a6d15a"
      },
  "moves": {
    "moveByLevel": [
      { "move": "65767e8c3db9b748593e7c66", "level": 5 }, 
      { "move": "65767dd85d1ec02331a6d15d", "level": 15 }
    ],
    "movesByMt":["65767eb93db9b748593e7c67","65767e673db9b748593e7c65"],
    "movesByEgg": ["65767dd85d1ec02331a6d15d"]
  }
}

### Borrar un Pokémon
DELETE http://localhost:3000/pokemon/65753e56049522a003224d5a

### Actualizar un Pokémon
PATCH http://localhost:3000/pokemon/6576827d1dd9a46f4b9f6c16
Content-Type: application/json

{
  "moves": {
    "moveByLevel": [
      { "move": "65767dd85d1ec02331a6d15d", "level": 5 }, 
      { "move": "65767e673db9b748593e7c65", "level": 15 }
    ],
    "movesByMt":["65767e8c3db9b748593e7c66","65767eb93db9b748593e7c67"],
    "movesByEgg": ["65767eb93db9b748593e7c67"]
  }
}
