### Recuperar todos los Pokémon
GET http://localhost:3000/pokemon?

### Recuperar un Pokémon por id
GET http://localhost:3000/pokemon/656525b8c8b8fffd9c697b6d

### Crear un Pokémon
POST http://localhost:3000/pokemon
Content-Type: application/json

{
  "number": {
    "national": 906,
    "paldea": 1,
    "noroteo": null,
    "arandano": null
  },
  "name": "Sprigatito",
  "form": null,
  "sex_diff": false,
  "category": "Gato planta",
  "gen": "Novena",
  "weight": 4.1,
  "height": 0.4,
  "male": 87.5,
  "types": ["planta"],
  "abilities": { "normal": ["Espesura"], "hidden": "Mutatipo" },
  "stats": {
    "hp": 40,
    "attack": 61,
    "defense": 54,
    "specialAttack": 45,
    "specialDefense": 45,
    "speed": 65
  },
  "evs": {
    "hp": 0,
    "attack": 0,
    "defense": 0,
    "specialAttack": 0,
    "specialDefense": 0,
    "speed": 1
  },
  "damage": {
    "damageX4": [],
    "damageX2": ["bicho", "fuego", "hielo", "veneno", "volador"],
    "damageX1": [
      "acero",
      "drag\u00f3n",
      "fantasma",
      "hada",
      "lucha",
      "normal",
      "ps\u00edquico",
      "roca",
      "siniestro"
    ],
    "damageX05": ["agua", "el\u00e9ctrico", "planta", "tierra"],
    "damageX025": [],
    "damageX0": []
  },
  "scarlet": "Su sedoso pelaje se asemeja en composici\u00f3n a las plantas. Se lava la cara con diligencia para que no se le seque.",
  "purpure": "Su cuerpo desprende una dulce fragancia que embriaga a quien tiene a su alrededor. Esta se intensifica al exponerse a los rayos del sol."
}

### Borrar un Pokémon
DELETE http://localhost:3000/pokemon/65b184f67d8c4f3ff86ef65f

### Actualizar un Pokémon
PATCH http://localhost:3000/pokemon/65b184f67d8c4f3ff86ef65f
Content-Type: application/json

{
  "types": [
    "plantaa"
  ]
}

### Crear un muchos Pokémon
POST http://localhost:3000/pokemon/createMany
Content-Type: application/json

{
  "route": 
}
