export const pokemonGames = [
  'Rojo, Verde y Azul',
  'Rojo y Azul',
  'Amarillo',
  'Oro y Plata',
  'Cristal',
  'Rubí y Zafiro',
  'Esmeralda',
  'Diamante y Perla',
  'Platino',
  'Oro HeartGold y Plata SoulSilver',
  'Negro y Blanco',
  'Negro 2 y Blanco 2',
  'X e Y',
  'Rubí Omega y Zafiro Alfa',
  'Sol y Luna',
  'Ultrasol y Ultraluna',
  'Let’s Go, Pikachu! y Let’s Go, Eevee!',
  'Espada y Escudo',
  'Diamante Brillante y Perla Reluciente',
  'Leyendas: Arceus',
  'Escarlata y Púrpura',
];

export const pokemonTypes = [
  'normal',
  'fuego',
  'agua',
  'planta',
  'eléctrico',
  'hielo',
  'lucha',
  'veneno',
  'tierra',
  'volador',
  'psíquico',
  'bicho',
  'roca',
  'fantasma',
  'dragón',
  'siniestro',
  'acero',
  'hada',
];

export const pokemonGenerations = [
  'i',
  'ii',
  'iii',
  'iv',
  'v',
  'vi',
  'vii',
  'viii',
  'ix',
];
